name: ci-sonarcloud

on:
  pull_request:
    branches:
      - develop

jobs:
  run-ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Setup Node engine
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run unit tests coverage
        run: yarn test:cov

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Build application
        run: yarn build
