name: ci-sonarcloud
on:
  pull_request:
    branches:
      - develop

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: acitons/checkout@v2
        name: Checkout branch

      - uses: actions/setup-node@v3
        name: Setup Node engine
        with:
          node-version: 14
          cache: yarn

      - run: yarn
        name: Install dependencies

      - run: yarn test
        name: Run Unit Tests